'''
Numpy——Python开源的科学计算工具包
高级的数值编程工具
强大的N维数组对象：ndarray
对数组结构数据进行运算（不用遍历循环）
随机数、线性代数、傅立叶变换等功能

Numpy基础数据结构
Numpy通用函数
Numpy索引及切片
Numpy随机数
Numpy数据的输入输出

'''

# Numpy基础数据结构

In [7]:
# Numpy数组ndarray
# 注意与list打印出来的区别，list用，号分隔元素。array没有分隔。
# 引入numpy这个包，并改名为np
import numpy as np

# 用.array创建np的数组，类型是numpy.ndarray
# .array()是个方法，所以后面的小括号是必须的。
# 小括号里是要生成的数组的内容，可以用小括号()也可以用中括号[]
ar = np.array((1,2,3,4,5))
ar1 = np.array([1,2,3,4,5])
print(ar, type(ar))
print(ar1)

# 二三维数组
# 二维数组是由两个一维数组组成的。
# 三维数组是由两个二维数组组成的。
# 大家刚开始可能各种括号有些乱，我是这样区分的。
# 以[[1,2,3,4,5,],[6,7,8,9,10]]为例子：
# 最外层[]跟一维数组的理解一样。
# 内层[1,2,3,4,5,]是第一个一维数组
# 内层[6,7,8,9,10]是第二个一维数组
# 中间的,号是区分这两个数组
ar2 = np.array([[1,2,3,4,5,],[6,7,8,9,10]])
ar3 = np.array(([1,2,3,4,5],[6,7,8,9,10]))
print(ar2)
print('----------------------------')
print(ar3)
print('----------------------------')
# 三维数组
# 注意，由于元素中有字符，所以整个数组的元素都会变成字符。
ar4 = np.array([[(['a','b','c','d','e'],[1,2,3,4,5])],[(['a','b','c','d','e'],[6,7,8,9,10])]])

print('----------------------------')
print(ar3)
print('----------------------------')
print(ar4,type(ar4))

[1 2 3 4 5] <class 'numpy.ndarray'>
[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
----------------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
----------------------------
----------------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
----------------------------
[[[['a' 'b' 'c' 'd' 'e']
   ['1' '2' '3' '4' '5']]]


 [[['a' 'b' 'c' 'd' 'e']
   ['6' '7' '8' '9' '10']]]] <class 'numpy.ndarray'>


# 数组的生成方法

In [16]:
# 对于array生成数组的说明，.array()括号里可以是列表、元祖、数组、生成器等等
# 通过range()生成一个0-9的list,并通过array转换成数组。
ar_r = np.array(range(10))
print(ar_r,type(ar_r))
# 通过Numpy自己的arange直接生成数组。
ar_ar = np.arange(10)
print(ar_ar,type(ar_ar))

# 如果arange()括号里面的数带小数点的话，例如5.0就变成浮点型了。
ar_r1 = np.arange(5.0)
print(ar_r1,type(ar_r1))
# 跟range()一样，可以通过最后一个参数来控制步长。
print(np.arange(0,10,2))


# 通过列表直接生成数组时，前后两个列表如果元素个数不同的话，会导致的整个数组维度变化。
ar5 = np.array([[1,2,3,4,5,],[6,7,8,9,10,'a','b']])
ar5_1 = np.array([[1,2,3,4,5,],[6,7,8,9,10,]])
print(ar5)
print(ar5_1)
print('注意数组维度--->',ar5.ndim)
print('注意数组维度--->',ar5_1.ndim)
# .linspace()有五个常用参数（开始，结束，个数，是否包含最后一个数，显示步长），如果最后一个参数不指定就包括“开始”和“结束”这两个值。
# 注意
# 1、由于包括开始和结束，所以在进行间隔分段的时候经常出现带小数的，而且小数的位数很多。
# 2、想避开很多小数位的话，可以调整分隔数
# 3、如果步长参数retstep = True的话，那么生成的就是元祖了。

# 从1开始到15，共分12份
print(np.linspace(1,15,num = 12))

# 从1开始到15，共分11份
print(np.linspace(1,15,num = 11))

# 从1开始到15，共分10份,但不包含最后一个数15 retstep
print(np.linspace(1,15,num = 10,endpoint = False))
print('-----------------------------')

#从1开始到15，共分10份,显示步长
s = np.linspace(1,15,num = 10,retstep = True)
print(s)
print('注意是元祖--->',type(s))

# 通过下标访问的话，第一个是数组本身，第二个是步长
print('数组-->',s[0])
print('-----------------------------')
print('步长-->',s[1])

# zeros()/zeros_like()/ones()/ones_like() eye()

# .zeros()生成元素全部为0的数组，zeros(shape, dtype=float, order='C')
# .ones()生成元素全部为1的数组，ones(shape, dtype=None, order='C')

# 生成10个元素为0的数组
print('10个元素为0的数组：','\n',np.zeros(10))
# 生成10个元素为1的数组
print('10个元素为1的数组：','\n',np.ones(10))

# 生成2行5列的二维全0数组
# 注意括号里的写发，参数第一个是shape也就是形状，
print('2行5列二维数组--->','\n',np.zeros((2,5)))
print('3行5列二维数组--->','\n',np.zeros((3,5)))

s1 = np.zeros((2,3,5))
print('三维数组--->','\n',s1)
print('几维数组？？-->',s1.ndim)
# ones()同样是
print('2行5列二维数组--->','\n',np.ones((2,5)))
print('3行5列二维数组--->','\n',np.ones((3,5)))
s2 = np.ones((2,3,5))
print('三维数组--->','\n',s2)
print('几维数组？？-->',s2.ndim)
# .zeros_like()生成一个和参数形状相同的全0数组。
# .ones_like()生成一个和参数形状相同的全1数组。
print('前面定义的一个二维数组：','\n',ar2)
print('生成一个和ar2形状相同的全0数组：','\n',np.zeros_like(ar2))
print('生成一个和ar2形状相同的全1数组：','\n',np.ones_like(ar2))


# eye()生成一个正方的N×N的矩阵数组，其中对角线值为1，其他的为0
print('生成一个4×4的矩阵：','\n',np.eye(4))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[0. 1. 2. 3. 4.] <class 'numpy.ndarray'>
[0 2 4 6 8]
[list([1, 2, 3, 4, 5]) list([6, 7, 8, 9, 10, 'a', 'b'])]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
注意数组维度---> 1
注意数组维度---> 2
[ 1.          2.27272727  3.54545455  4.81818182  6.09090909  7.36363636
  8.63636364  9.90909091 11.18181818 12.45454545 13.72727273 15.        ]
[ 1.   2.4  3.8  5.2  6.6  8.   9.4 10.8 12.2 13.6 15. ]
[ 1.   2.4  3.8  5.2  6.6  8.   9.4 10.8 12.2 13.6]
-----------------------------
(array([ 1.        ,  2.55555556,  4.11111111,  5.66666667,  7.22222222,
        8.77777778, 10.33333333, 11.88888889, 13.44444444, 15.        ]), 1.5555555555555556)
注意是元祖---> <class 'tuple'>
数组--> [ 1.          2.55555556  4.11111111  5.66666667  7.22222222  8.77777778
 10.33333333 11.88888889 13.44444444 15.        ]
-----------------------------
步长--> 1.5555555555555556
10个元素为0的数组： 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
10个元素为1的数组： 
 [1. 1. 1. 1.

In [10]:
# ndarray.ndim 查看数组的维度，也就是看是几维数组
# 查看之前定义的ar、ar2和ar4是几维数组
print(ar.ndim)
print(ar2.ndim)
print(ar4.ndim)

1
2
4


In [11]:
# ndarray.shape 查看数组的形状或者说是尺寸，就是几行几列 如n行m列（n，m）

# ar是0行列5列
# ar2是2行5列
print(ar.shape)
print(ar2.shape)

# 看一个特别的例子
ar6 = np.array([[1],[2]])
print(ar6,'\n',ar6.shape)

(5,)
(2, 5)
[[1]
 [2]] 
 (2, 1)


In [12]:
# ndarray.size 查看数组中元素的总个数
print(ar.size)
print(ar2.size)
print(ar4.size)

5
10
20


In [13]:
# ndarray.dtype 查看数组中元素的类型。
# 另外NumPy提供它自己的类型。numpy.int32，numpy.int16和numpy.float64是一些例子。
# 注意与.type的区别

print(type(ar2),'\n',ar2.dtype)

<class 'numpy.ndarray'> 
 int32


In [14]:
# ndarray.itemsize 查看数组中每个元素的字节大小
print(ar2.itemsize)

4


In [15]:
# ndarray.data 查看数组中元素的缓冲区。
# 一般很少会用到这个，用的比较多的是用索引来范围各个元素。
print(ar3.data)

In [144]:
# 作业1
zy1 = np.array((1,2,'a','hello',[1,2,3],{'two':200,'three':200}))
print(type(zy1[4]))
print(type(zy1[-1]))
print(zy1)
print(zy1.shape)

#作业2
zy2 = np.array([[1,2,3,4,5,6,],['a','b','c','d','e','f'],['True','False','True','False','True','True']])
print(zy2)
print(zy2.shape)

#作业3
zy3 = np.linspace(5,15,num = 10,endpoint = False)
print(zy3)

#作业4
print(np.zeros((4,4)))
print(np.ones((3,3)))
print(np.eye(3))

<class 'list'>
<class 'dict'>
[1 2 'a' 'hello' list([1, 2, 3]) {'two': 200, 'three': 200}]
(6,)
[['1' '2' '3' '4' '5' '6']
 ['a' 'b' 'c' 'd' 'e' 'f']
 ['True' 'False' 'True' 'False' 'True' 'True']]
(3, 6)
[ 5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
