## Numpy的索引和切片
#### 1、索引和分片的主要作用是查找数据，通过索引和切片能够快速的定位到需要的数据。在后期的数据清洗、数据整理等方面都要用到。
#### 2、Numpy的索引和切片主要分为：基本索引和切片 / 布尔型索引和切片

In [1]:
import numpy as np

### 基本索引和切片

In [2]:
# Numpy中索引和切片的基本操作
# 一维数组
# 一维数组类似list。
ar1 = np.arange(20)
print('一维数组ar1：', ar1)
# 对数组进行索引，索引的下标是从0开始的。
print('数组ar1中下标为1的元素：', ar1[1])
# 切片的时候在[]中是左包含右不包含的，例如[:3]表示的是下标为0、1、2的3个下标。
print('数组ar1中下标从0-2的元素：', ar1[:3])
# 在索引和切片中加入步长，步长可以理解为间隔几个。步长为2的话就是间隔1个，步长为3就是间隔2个。技巧，步长数-1。
print('数组ar1中从第一个元素开始显示，但步长是2', ar1[::2])
print('数组ar1中从第一个元素开始显示，但步长是3', ar1[::3])
print('---------------------------------------------')

# 二维数组
# 二维数组的索引在写参数的时候是先行后列。
ar2 = np.arange(9).reshape(3,3)
print('二维数组ar2: ', '\n', ar2)

# 二维数组单一下标表示的是数组的某一个整行
print('数组ar2中第二行的所有元素: ', ar2[1])
# 二维数组双下标表示的整行元素中的某一个元素。
print('数组ar2中第二行的所有元素中的下标为1的元素: ', ar2[1][1])
# 二维数组中某个元素的第二种写法
print('数组ar2中第二行的所有元素中的下标为1的元素: ', ar2[1,1])
# ar2中从第一行开始到最后一行的前一行，第三列开始到最后一列的前一列。的所有元素。
# 上面这句话比较绕口，只要注意左包含右不包含就很好理解了。
print(ar2[:2,2:])
print('---------------------------------------------')

# 三维数组
# 3个2行2列的二维数组组成一个三维数组。
# reshape的参数一般是由高往低写。如果是reshape(3,4,4)那就是3个4行4列的三维数组。
# 可通过.ndim来看数组的维度。
ar3 = np.arange(12).reshape(3,2,2)

# 下面是4维数组的例子，reshape(3,4,4,2)的意思是3个三维数组组成，三维数组又是由4个4行2列的二维数组组成的。
# ar3 = np.arange(96).reshape(3,4,4,2)

print('三维数组ar3: ', '\n', ar3, '\n', ar3.ndim)
print('三维数组ar3中第三个二维数组: ', '\n', ar3[2])
print('三维数组ar3中第三个二维数组的第二行: ', '\n', ar3[2][1])
print('三维数组ar3中第三个二维数组的第二行的第二元素: ', '\n', ar3[2][1][1])

一维数组ar1： [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
数组ar1中下标为1的元素： 1
数组ar1中下标从0-2的元素： [0 1 2]
数组ar1中从第一个元素开始显示，但步长是2 [ 0  2  4  6  8 10 12 14 16 18]
数组ar1中从第一个元素开始显示，但步长是3 [ 0  3  6  9 12 15 18]
---------------------------------------------
二维数组ar2:  
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
数组ar2中第二行的所有元素:  [3 4 5]
数组ar2中第二行的所有元素中的下标为1的元素:  4
数组ar2中第二行的所有元素中的下标为1的元素:  4
[[2]
 [5]]
---------------------------------------------
三维数组ar3:  
 [[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]] 
 3
三维数组ar3中第三个二维数组:  
 [[ 8  9]
 [10 11]]
三维数组ar3中第三个二维数组的第二行:  
 [10 11]
三维数组ar3中第三个二维数组的第二行的第二元素:  
 11


### 布尔型索引和切片

In [3]:
# 布尔型索引中保留的都是True，舍去的都是False。
ar3 = np.arange(9).reshape(3,3)
print(ar3)
print('---------------------------------')
# 定义a b两个布尔型的数组。
a = np.array([True,False,True])
b = np.array([False,True,False])
print(a, '\n', b)
print('---------------------------------')
# ar3[a]的意思是：根据数组a中True的位置，来显示数组ar3的元素。
# 因为数组a的True的位置是第一行和第三行，所以在对数组ar3进行显示的时候就舍去了第二行
print(ar3[a])
print('---------------------------------')
# ar3[a, :2]的意思是：先根据数组a中True的位置，来定位到数组ar3的第一行和第三行。
# 又因为有 :2的限制条件，所以显示第一行和第三行的第一列和第二列元素
print(ar3[a, :2])
print('---------------------------------')
# ar3[:,b]的意思是：先把数组ar3的所有元素都准备好，然后根据布尔型数组b来判断取舍哪一列。
# 注意：索引都是先写行再写列。
print(ar3[:,b])
print('---------------------------------')
# 先获得一个新的布尔型数组。
ar4 = ar3>4
print(ar4)
# ar3[ar4]的意思是，根据布尔型数组ar4里True的位置，来保留数组ar3里的元素。
print(ar3[ar4])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
---------------------------------
[ True False  True] 
 [False  True False]
---------------------------------
[[0 1 2]
 [6 7 8]]
---------------------------------
[[0 1]
 [6 7]]
---------------------------------
[[1]
 [4]
 [7]]
---------------------------------
[[False False False]
 [False False  True]
 [ True  True  True]]
[5 6 7 8]


In [5]:
# 数组索引和切片的值修改和复制
# 赋值给一个索引/切片时，会改变原数组
ar5 = np.arange(10)
print(ar5)
ar5[5] = 100
ar5[7:9] = 666
print(ar5)
print('------------------------------')
# 复制
ar6 = np.arange(10)
# 这里需要注意的是.copy是将原数组的值赋给新数组，也就是传值。改变一个不会影响另外一个。
ar7 = ar6.copy()
ar7[7:9] = 200
print(ar6)
print(ar7)


# # 下面这部分代码是传址，也就是把内存中的地址传递给新的数组。这样改变任何一个都会影响另外一个。
# ar6 = np.arange(10)
# ar8[7:9] = 200
# print(ar6)
# print(ar8)


[0 1 2 3 4 5 6 7 8 9]
[  0   1   2   3   4 100   6 666 666   9]
------------------------------
[0 1 2 3 4 5 6 7 8 9]
[  0   1   2   3   4   5   6 200 200   9]
